name: Compile Verilog and VHDL Files

on:
  push:
    paths:
      - '**/*.v'
      - '**/*.sv'
      - '**/*.vhd'
      - '**/*.vhdl'
  pull_request:
    paths:
      - '**/*.v'
      - '**/*.sv'
      - '**/*.vhd'
      - '**/*.vhdl'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Verilog & VHDL Tools
      run: |
        sudo apt update
        sudo apt install -y iverilog ghdl

    - name: Find and Compile Verilog Files
      run: |
        echo "Compiling Verilog files..."
        find . -type f \( -iname "*.v" -o -iname "*.sv" \) | while read file; do
          echo "Compiling $file"
          iverilog -o /tmp/out "$file" 2> /tmp/verilog_errors.log
          if [ $? -ne 0 ]; then
            echo "::error file=$file::$(cat /tmp/verilog_errors.log)"
            exit 1
          fi
        done

    - name: Find and Analyze VHDL Files
      run: |
        echo "Analyzing VHDL files..."
        find . -type f \( -iname "*.vhd" -o -iname "*.vhdl" \) | while read file; do
          echo "Analyzing $file"
          ghdl -a "$file" 2> /tmp/vhdl_errors.log
          if [ $? -ne 0 ]; then
            echo "::error file=$file::$(cat /tmp/vhdl_errors.log)"
            exit 1
          fi
        done
