name: Compile Verilog and VHDL Files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  compile-hdl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install HDL tools
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog ghdl

      - name: Find and compile Verilog and VHDL files
        run: |
          set -e
          # Find and compile Verilog files
          find . -type f \( -name "*.v" -o -name "*.sv" \) | while read verilog_file; do
            echo "Compiling $verilog_file"
            iverilog -o /tmp/$(basename "$verilog_file").out "$verilog_file" 2> /tmp/iverilog_err.log || {
              echo "::error file=$verilog_file::$(cat /tmp/iverilog_err.log)"
              exit 1
            }
          done
          # Find and compile VHDL files
          find . -type f \( -name "*.vhd" -o -name "*.vhdl" \) | while read vhdl_file; do
            echo "Analyzing $vhdl_file"
            ghdl -a "$vhdl_file" 2> /tmp/ghdl_err.log || {
              echo "::error file=$vhdl_file::$(cat /tmp/ghdl_err.log)"
              exit 1
            }
          done
