name: HDL Compiler Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  hdl-compile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install HDL tools
      run: |
        sudo apt-get update
        sudo apt-get install -y ghdl iverilog
        
    - name: Find HDL files
      id: find-files
      run: |
        echo "Finding Verilog and VHDL files..."
        find . -type f \( -name "*.v" -o -name "*.vhd" -o -name "*.vhdl" -o -name "*.sv" \) > hdl_files.txt
        echo "Found files:"
        cat hdl_files.txt
        
    - name: Compile Verilog files
      run: |
        echo "Compiling Verilog files..."
        verilog_files=$(find . -type f \( -name "*.v" -o -name "*.sv" \))
        compile_error=false
        
        for file in $verilog_files; do
          if [ -f "$file" ]; then
            echo "Compiling: $file"
            if ! iverilog -o /tmp/compiled_$(basename "$file" .v) "$file" 2>&1; then
              echo "❌ ERROR in file: $file"
              iverilog -o /tmp/compiled_$(basename "$file" .v) "$file" 2>&1 | while IFS= read -r line; do
                if [[ $line == *":"* ]] && [[ $line == *"error"* ]]; then
                  echo "  📍 $line"
                fi
              done
              compile_error=true
            else
              echo "✅ $file compiled successfully"
            fi
          fi
        done
        
        if [ "$compile_error" = true ]; then
          echo "Verilog compilation failed!"
          exit 1
        fi
        
    - name: Compile VHDL files
      run: |
        echo "Compiling VHDL files..."
        vhdl_files=$(find . -type f \( -name "*.vhd" -o -name "*.vhdl" \))
        compile_error=false
        
        for file in $vhdl_files; do
          if [ -f "$file" ]; then
            echo "Compiling: $file"
            if ! ghdl -a "$file" 2>&1; then
              echo "❌ ERROR in file: $file"
              ghdl -a "$file" 2>&1 | while IFS= read -r line; do
                if [[ $line == *":"* ]] && [[ $line == *"error"* ]]; then
                  echo "  📍 $line"
                fi
              done
              compile_error=true
            else
              echo "✅ $file compiled successfully"
            fi
          fi
        done
        
        if [ "$compile_error" = true ]; then
          echo "VHDL compilation failed!"
          exit 1
        fi
        
    - name: Summary
      if: always()
      run: |
        echo "HDL Compilation Summary:"
        echo "======================="
        total_files=$(find . -type f \( -name "*.v" -o -name "*.vhd" -o -name "*.vhdl" -o -name "*.sv" \) | wc -l)
        echo "Total HDL files found: $total_files"
        
        if [ $? -eq 0 ]; then
          echo "🎉 All files compiled successfully!"
        else
          echo "❌ Some files failed to compile. Check the logs above for details."
        fi
